/**
 * JavaCC template file created by SF JavaCC plugin 1.5.28+ wizard for JavaCC 1.5.0+
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 */
options
{
  static = true;
}

PARSER_BEGIN(MySQL)

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Polygon;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.spec.EncodedKeySpec;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import java.util.Scanner;
import java.util.Set;
import java.io.IOException;

public class MySQL
{
  public static int state=1001;
  public static int LEX=1001;
  public static int AST=1002;
  public static int SDD=1003;
  public static int SDT=1004;
  public static String CurrentDatabase="";
  public static String CurrentTable="";
  public static Create SQL_create = new Create();
  public static Drop SQL_drop = new Drop();
  public static Use SQL_use = new Use();
  public static Show SQL_show = new Show();
  public static Insert SQL_insert = new Insert();

  //在调用的时候需要静态，因为是在main函数
  public static Select SQL_select ;//= new Select();

  public static void main(String args []) throws ParseException
  {
     
      MySQL parser;
    
      parser = new MySQL(System.in);
      System.out.println("============================");
      System.out.println("欢迎使用简单版本的MYSQL编译器");
      System.out.println("版本号：0049");
      System.out.println("Welcome to the easy MYSQL");
      System.out.println("Version 0049");





      System.out.println("============================");
       while (true)
    {
      // System.out.println("Reading from standard input...");
      System.out.println();
      System.out.print("MYSQL>>");
      // System.out.println();
      try
      {
        MySQL.one_line();

      }
      catch (Exception e)
      {
        System.out.println("NOK.");
        System.out.println(e.getMessage());
        MySQL.ReInit(System.in);
      }
      catch (Error e)
      {
        System.out.println("Oops.");
        System.out.println(e.getMessage());
        break;
      }
    }
  }
  
}

PARSER_END(MySQL)



//TOKEN: 这个产生式中的正则表达式描述了tokens的语法，主要定义语法分析阶段用到的非终结符。 
//Token Manager会根据这些正则表达式生成 Token 对象并返回给parser。
//SPECIAL_TOKEN: 这产生式中的正则表达式描述了特殊的Token。特殊的Token是在解析过程中没有意义的Token，也就是本BNF产生式忽略的Token。但是，这些Token还是会被传递给parser，并且parser也可以访问他们。访问特殊Token的方式是通过其相邻的Token的specialToken域。特殊Token在处理像注释这种token的时候会非常有用。可以参考这个文档以了解更多关于特殊token的知识。
//SKIP: 这个产生式的规则命中的Token会被Token Manager丢弃掉。
//MORE: 有时候会需要逐步地构建Token。被这种规则命中的Token会存到一个Buffer中，直到遇到下一个Token或者Special_token，然后他们和最后一个Token或者Special_token会连在一起作为一个Token返回给parser。如果一个More后面紧跟了一个SKIP，那么整个Buffer中的内容都会被丢弃掉。
//


ControlSQL CompilationUnit() : {
Token head ;
} {
  "HEADER"
{ head = getToken( 1 ) ; 
System.out.println(head);}

{ return new ControlSQL( head, getToken(0) ) ; }
}


SKIP :
{
  " "
| "\r"
| "\t"
| "\n"
}



TOKEN : //创建库，表。
{
      <CREATE:"CREATE">
  |   <DATABASE:"DATABASE">
  |   <SHOW:"SHOW">
  |   <DATABASES:"DATABASES">
  |   <DROP:"DROP">
  |   <USE:"USE">
  |   <TABLE:"TABLE">
  |   <TABLES:"TABLES">
  |   <INSERT:"INSERT">  
  |   <AND: "AND">
  |   <ANY: "ANY">
  |   <AS: "AS">
  |   <ASC:"ASC">
  |   <BEGIN: "BEGIN">
  |   <BETWEEN:"BETWEEN">
  |   <BINARY_INTEGER: "BINARY_INTEGER">
  |   <BOOLEAN:"BOOLEAN">
  |   <BY:"BY">
  |   <CHAR:"CHAR">
  |   <CLOSE:"CLOSE">
  |   <COMMENT:"COMMENT">
  |   <COMMIT:"COMMIT">
  |   <CONNECT:"CONNECT">
  |   <CONSTANT:"CONSTANT">
  |   <CURRENT:"CURRENT">
  |   <CURSOR:"CURSOR">
  |   <DATE:"DATE">
  |   <DECIMAL:"DECIMAL">
  |   <DELETE:"DELETE">
  |   <DESC:"DESC">
  |   <DISTINCT:"DISTINCT">
  |   <DO:"DO">
  |   <ELSE:"ELSE">
  |   <ELSIF:"ELSIF">
  |   <END:"END">
  |   <EXCEPTION:"EXCEPTION">
  |   <EXCEPTION_INIT:"EXCEPTION_INIT">
  |   <EXCLUSIVE:"EXCLUSIVE">
  |   <EXISTS:"EXISTS">
  |   <EXIT:"EXIT">
  |   <FETCH:"FETCH">
  |   <FLOAT:"FLOAT">
  |   <FOR:"FOR">
  |   <FROM:"FROM">
  |   <FUNCTION:"FUNCTION">
  |   <GOTO:"GOTO">
  |   <GROUP:"GROUP">
  |   <HAVING:"HAVING">
  |   <INTERSECT:"INTERSECT">
  |   <INTO:"INTO">
  |   <IS:"IS">
  |   <LEVEL:"LEVEL">
  |   <LIKE:"LIKE">
  |   <LOCK:"LOCK">
  |   <LOOP:"LOOP">
  |   <MINUS:"MINUS">
  |   <MODE:"MODE">
  |   <NATURAL:"NATURAL">
  |   <NOT:"NOT">
  |   <NOWAIT:"NOWAIT">
  |   <NULL:"NULL">
  |   <NUMBER:"NUMBER">
  |   <OF:"OF">
  |   <ONLY:"ONLY">
  |   <OPEN:"OPEN">
  |   <OR:"OR">
  |   <ORDER:"ORDER">
  |   <OTHERS:"OTHERS">
  |   <OUT:"OUT">
  |   <PACKAGE:"PACKAGE">
  |   <POSITIVE:"POSITIVE">
  |   <PRAGMA:"PRAGMA">
  |   <PRIOR:"PRIOR">
  |   <PROCEDURE:"PROCEDURE">
  |   <RAISE:"RAISE">
  |   <READ:"READ">
  |   <REAL:"REAL">
  |   <RECORD:"RECORD">
  |   <REF:"REF">
  |   <RETURN:"RETURN">
  |   <REVERSE:"REVERSE">
  |   <ROLLBACK:"ROLLBACK">
  |   <ROW:"ROW">
  |   <SAVEPOINT:"SAVEPOINT">
  |   <SEGMENT:"SEGMENT">
  |   <SELECT:"SELECT">
  |   <SET:"SET">
  |   <SHARE:"SHARE">
  |   <SMALLINT:"SMALLINT">
  |   <SQL:"SQL">
  |   <THEN:"THEN">
  |   <TO:"TO">
  |   <TRANSACTION:"TRANSACTION">
  |   <UNION:"UNION">
  |   <UPDATE:"UPDATE">
  |   <VARCHAR2:"VARCHAR2">
  |   <VARCHAR:"VARCHAR">
  |   <WHEN:"WHEN">
  |   <WHERE:"WHERE">
  |   <WHILE:"WHILE">
  |   <WITH:"WITH">
  |   <WORK:"WORK">
  |   <WRITE:"WRITE">
  
  |   <MYSQL_OVER:"MYSQL_OVER">
  |   <LEFTBRCKET:"(">
  |   <RIGHTBRCKET:")">
  |   <INT:"INT">
  |   <VALUES:"VALUES">
  |   <SingleQuotes:"'">
  |   <ALL:"ALL">
  |   <DISTINCTROW:"DISTINCTROW">
  |   <TOP:"TOP"> 

}
TOKEN : /* Numeric Constants */
{	
   		< SQL_CONSTANT: ( <DIGIT> )+ >
  | 	< DIGIT: ["0" - "9"] >
 

}

SPECIAL_TOKEN://描述注释
{
   <LINE_COMMENT: "--"(~["\r","\n"])*>
|  <MULTI_LINE_COMMENT: "/*" (~["*"])* "*" ("*" | (~["*","/"] (~["*"])* "*"))* "/">
}



TOKEN://描述标识符
{
	< SQL_IDENTIFIER: ( <LETTER> )+ ( <DIGIT> | <LETTER> |<SPECIAL_CHARS>)* >
| 	< #LETTER: ["a"-"z", "A"-"Z"] >
|   < #SPECIAL_CHARS: "$" | "_">
|   < SQL_BIND: ":" <SQL_IDENTIFIER> ("." <SQL_IDENTIFIER>)? >
|   < SQL_CHAR_LITERAL: "'" (~["'"])* "'" ("'" (~["'"])* "'")*>
|   < SQL_QUOTED_IDENTIFIER: "\"" (~["\n","\r","\""])* "\"" >
}


// TOKEN://表述逻辑符号
// {
//   < COMPARE:"=">//(["="]["!="]["<>"][">"][">="]["<"]["<="]) >
// }

Token compare():
{}
{
 ( "=" | "!="  | "<>" | ">" | ">=" | "<" | "<=")
  {
    return MySQL.token;
  }
}


int input():
{}
{
  ";" { System.out.println(" call function ");
      return 0;}
}

//用来循环处理命令
//参考自带的模板
void one_line() :
{}
{
  Statement()

}

void TestStatement() :
{}
{
  CompilationUnit()";"{
    System.out.println("CompilationUnit");
  }

}

void Statement():
{}{
  TestStatement()
  |
  CreadStatement()
  // {
  //   System.out.println("begin CreadStatement");
  // }
  |
  ShowStatement()
  // {
    
  //   System.out.println("begin ShowStatement");
  // }
  |
  USEStatement()
  |
  DropStatement()
  |
  InsertStatement()
  |
  SelectStatement()
  |
  DeleteStatement()
  |
  UpdateStatement()

}

void STOPStatement():
{}{
    "MYSQL_OVER"";"{
      System.out.println("EXIT");
    }
}

void CreadStatement():
{
  Token Token;
}{
      "CREATE" (CreatTable()|CreatDatabase()) ";"
      

}

void CreatTable():
{
  Token Token;
}{

  Token="TABLE"
  {System.out.println(Token);

    if(MySQL.state==MySQL.SDT){
      SQL_create.setCurrentDatabase(CurrentDatabase);
    }

  
  }
  TableItem() 
  {
    if(MySQL.state==MySQL.SDT){
      try {
        System.out.println("写表");
        SQL_create.WriteTable();
      } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
      }
    }
  }

}
void TableItem():
{}{ 

  IdentifierItem()
  {
    if(MySQL.state==MySQL.AST){
      System.out.print("TableName  :   ");
      System.out.println(MySQL.token);

    }
    if(MySQL.state==MySQL.SDT&&CurrentDatabase!=""){
      
      System.out.println(SQL_create.getCurrentDatabase());
      SQL_create.CreateTable(MySQL.token.toString());
      CurrentTable=SQL_create.getTable();
      // System.out.println(SQL_create.getTable());


      
    }
    
   
  }
 [ <LEFTBRCKET>
  AttributeItem()
  <RIGHTBRCKET>
  {
    System.out.println("create A table with AttributeItem ");
  }]



}
//这里声明列表的时候，容易犯错误
//比如 格式上应该是 标识符-变量-变量值 应该看作一个整体
//之前把标识符和变量分开了。导致无法识别循环识别第二个列表属性
void AttributeItem():
{}
{
  {
   if(MySQL.state==MySQL.AST){
    System.out.println("============================");
    System.out.println("AttributeItems");

   } 
    }
  
  BasicDataTypeDeclaration() 
  ("," BasicDataTypeDeclaration() )*


  {
    // if(MySQL.state==MySQL.SDT){
    //   System.out.print("语法制导翻译 写表 ： ");
    //   SQL_create.getExpression();
    // }
  }

  
  {if(MySQL.state==MySQL.AST)
    System.out.println("============================");}

}

void BasicDataTypeDeclaration():
{}
{
  

  (IdentifierItem()

          {//打印属性名
         if(MySQL.state==MySQL.AST){
           System.out.print(MySQL.token+"   :   ");
     
         }
         if(MySQL.state==MySQL.SDT){
          System.out.print("语法制导翻译 列名 ： ");

           SQL_create.setColumn_name(MySQL.token.toString());
           System.out.println(SQL_create.getColumn_name());
     
         }
     
         if(MySQL.token!=null&&MySQL.state==MySQL.AST){
           //打印属性类型
           System.out.println(MySQL.token.next);
           
       
         }
         if(MySQL.state==MySQL.SDT){
          System.out.print("语法制导翻译 列类型： ");
           SQL_create.setColumn_value(MySQL.token.next.toString());
           System.out.println(SQL_create.getColumn_value());
         }

         if(MySQL.state==MySQL.SDT){
          System.out.print("语法制导翻译 加属性 ： ");
          SQL_create.getExpression();
        }
         
       }


      ( (       "CHAR"
       |   "VARCHAR"
       |   "VARCHAR2"
       |   "REAL"
       |   "FLOAT" 
   ) [ "(" <SQL_CONSTANT>  ")" ]

   |   "INT"
   |   "DATE"
   |   "BINARY_INTEGER"
   |   "BOOLEAN" )
  
  
  
  )
  
//   ( IdentifierItem()
//
//         {//打印属性名
//          if(MySQL.state==MySQL.AST){
//            System.out.print(MySQL.token+"   :   ");
//      
//          }
//          if(MySQL.state==MySQL.SDT){
//            SQL_create.setColumn_name(MySQL.token.toString());
//      
//          }
//      
//          if(MySQL.token!=null&&MySQL.state==MySQL.AST){
//            //打印属性类型
//            System.out.println(MySQL.token.next);
//            
//        
//          }
//          if(MySQL.state==MySQL.SDT){
//            SQL_create.setColumn_value(MySQL.token.next.toString());
//          }
//          
//        }
//
//
//
//
//    ( (       "CHAR"
//        |   "VARCHAR"
//        |   "VARCHAR2"
//        |   "REAL"
//        |   "FLOAT" 
//    ) [ "(" <SQL_CONSTANT>  ")" ]
//
//    |   "INT"
//    |   "DATE"
//    |   "BINARY_INTEGER"
//    |   "BOOLEAN" )
//    )
    
    // {if(MySQL.token.image!=")")
    //   System.out.println(MySQL.token);
    // }



    



   
}

void CreatDatabase():
{
  Token Token;
}{
  "DATABASE"
  Token=IdentifierItem()
  {
    if(MySQL.state==MySQL.AST)
    System.out.println("create A database = "+Token);
      if(MySQL.state==MySQL.SDT){
    SQL_create.CreateDatabase(Token.toString());
    CurrentDatabase=SQL_create.getCurrentDatabase();
    System.out.println("语法制导翻译 = "+SQL_create.getCurrentDatabase());
  }
  }

}

void ShowStatement():
{  }
{
  "SHOW" (ShowDatabases()|ShowTables()) ";"
  {
    
    // System.out.println("ShowStatement");
    
  }
}

void ShowDatabases():
{}{
  "DATABASES" 
  {
    if(MySQL.state==MySQL.AST){
      System.out.println("ShowDatabases");
    }
    if(MySQL.state==MySQL.SDT){
      
      System.out.println("语法制导翻译 ： ");
      if(SQL_show.ShowDatabase()==false){
        System.out.println("打印数据库失败");
      }

    }



  }
}




void ShowTables():
{}{
 "TABLES"
 {
   if(MySQL.state==MySQL.AST){
    System.out.println("ShowTables");

   }
  

  if(MySQL.state==MySQL.SDT){
    SQL_show.setCurrentDatabase(CurrentDatabase);
    System.out.println("语法制导翻译 ： ");
    if(SQL_show.ShowTable()==false){
      System.out.println("打印表失败");
    }

  }



 }
}




void DropStatement():
{}{
 "DROP" (DropDatabase()|DropTable())";"
}



void DropDatabase():
{
  Token temp;
}{
  "DATABASE" (temp=IdentifierItem())
  {
    if(MySQL.state==MySQL.AST)
    {
      System.out.println("DropDatabase = "+temp);
    }
    if(MySQL.state==MySQL.SDT){
      SQL_drop.setCurrentDatabase(CurrentDatabase);
      SQL_drop.DropDatabase(CurrentDatabase);
    }

    
  }
}






void DropTable():
{
  Token temp;
}{
  "TABLE" (temp=IdentifierItem())
  {
    if(MySQL.state==MySQL.AST){
      System.out.println("DropTable = "+temp);
    }
    



    if(MySQL.state==MySQL.SDT){
      SQL_drop.setCurrentDatabase(CurrentDatabase);
      SQL_drop.DropTable(CurrentTable);
    }

  }
  
}





void USEStatement ():
{
  Token temp;
}
{
 "USE" temp=IdentifierItem()";"

 {
  if(MySQL.state==MySQL.AST){
    System.out.println("USEStatement = "+temp);

  }
  if(MySQL.state==MySQL.SDT){

    CurrentDatabase=temp.toString();

  }

 }
//  {
//   if(MySQL.state==MySQL.AST) { 
//    System.out.println("USEStatement = "+temp);
//     }
//   if(MySQL.state==MySQL.SDT) { 
//     CurrentDatabase=temp.toString();
//   }
//   }
}




//INSERT
//INSERT INTO 表名称 VALUES (值1, 值2,....)
//INSERT INTO table_name (列1, 列2,...) VALUES (值1, 值2,....)

void InsertStatement():
{
  Token temp;
}
{
  "INSERT" "INTO" 
   temp=IdentifierItem() 
  { if(MySQL.state==MySQL.LEX)
    {
      System.out.println("INSERT SUCCESS");
    }
    
    if(MySQL.state==MySQL.AST)
    {
      System.out.println("TABLE = "+temp);
    }
    

    if(MySQL.state==MySQL.SDT&&CurrentDatabase!=""){
      System.out.println("语法制导翻译：");
      SQL_insert.setCurrentDatabase(CurrentDatabase);
      if(SQL_insert.CheckTable(temp.toString())==false){
        System.out.println("进入错误数据表");
        return;

      }
      CurrentTable=temp.toString();
      SQL_insert.setCurrentTable(CurrentTable);
      try {
        //不管是value还是column都提前初始化
        SQL_insert.Init();
      } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
      }



    }
  }

  {
    if(MySQL.state==MySQL.SDT){
      try{
        if(SQL_insert.CheckColumn(CurrentTable)==false){
          System.out.println("无效字段或者类型");
          return;
        }

      }catch (IOException e){
        e.printStackTrace();

      }

      SQL_insert.setOperationColumn(true);





    }
  }






  // [TableColumns()]
  (TableColumns() | TableValues())
  // TableValues()
   ";" 
}


void TableValues():
{
  Token temp;
}{
   "VALUES"
  "("
   TableValue() ("," TableValue())*
  ")"

  {
//有列表插入列表，没有列表直接插入值。分开来考虑会更清楚
    if(MySQL.state==MySQL.SDT)
    {
      if(SQL_insert.isOperationColumn()==true&&SQL_insert.isWithColumn()==false){


        try {
          if(SQL_insert.DirectInsertValue(CurrentTable)==true){
              System.out.println("插入数值成功");
            }
        } catch (IOException e) {
          // TODO Auto-generated catch block
          e.printStackTrace();
        }

      }

      



    }



  }
}

void TableValue():
{
  Token temp;
}{
  (
    temp=IdentifierItem()
    {
      if(MySQL.state==MySQL.AST)
      {
        System.out.println("TABLEVALUE = "+temp);

      }
      

      if(MySQL.state==MySQL.SDT)
      {
        System.out.println("TABLEVALUE = "+temp);
        SQL_insert.getValue_columm().add(temp.toString());

      }




    }
    
    // <SingleQuotes> <SQL_IDENTIFIER> <SingleQuotes>
    // ObjectName()  |
  //  (<SQL_CHAR_LITERAL>IdentifierItem() <SQL_CHAR_LITERAL>)
   
  )
}


void TableColumns():
{
  Token temp;
}{



   "("
   TableColumn()("," TableColumn())*
   ")"

   {
    SQL_insert.setWithColumn(true);

   }


   TableValues()

   {
    if(MySQL.state==MySQL.SDT&&SQL_insert.isOperationColumn()==true){
      try{
        if(SQL_insert.InsertValueWithColumn(SQL_insert.getCurrentTable())==true){
          System.out.println("列表和数据插入成功");
        }else{
          System.out.println("列表和数据插入失败");
  
        }

      }catch (IOException e){
        e.printStackTrace();

      }
      



    }



   }




}

void TableColumn():
{
  Token temp;
}{
  temp=IdentifierItem()
  {

    if(MySQL.state==MySQL.AST){
      System.out.println("TABLECOLUMN = "+temp);
    }

    if(MySQL.state==MySQL.SDT){
      try {
        if(SQL_insert.CheckColumn(CurrentTable)==false){
          System.out.println("无效字段或者类型");
          return;
        }
        
      } catch (Exception e) {
        e.printStackTrace();
        
      }


      SQL_insert.getTable_column().add(temp.toString());



    }
    




   }
}

// void TableColumn():
// {}
// {
//     // user.table.column
//     ObjectName() [ "." ObjectName() ["." ObjectName()]]
// }



//SELECT 列名称 FROM 表名称
//SELECT * FROM 表名称
//SELECT 列名称 FROM 表名称 WHERE 列 运算符 值
//SELECT * FROM Persons WHERE FirstName='Thomas' AND LastName='Carter'
//SELECT Company, OrderNumber FROM Orders ORDER BY Company



// SELECT[ALL|DISTINCT|DISTINCTROW|TOP]
// {*|talbe.*|[table.]field1[AS alias1][,[table.]field2[AS alias2][,…]]}
// FROM tableexpression[,…][IN externaldatabase]
// [WHERE…]
// [GROUP BY…]
// [HAVING…]
// [ORDER BY…]

void SelectStatement():
{}
{
  "SELECT" ["ALL"|"DISTINCT"|"DISTINCTROW"|"TOP"]
  {

    if(MySQL.state==MySQL.SDT){
      SQL_select = new Select();
      SQL_select.setCurrentDatabase(CurrentDatabase);
      

    }



  }

  {
      SelectBaseStatement();
    
  }



  
   ";"
   {



    if(MySQL.state==MySQL.LEX){
      System.out.println(" SELECT SUCCESS");

    }
    
    if(MySQL.state==MySQL.SDT){
      System.out.println(" SELECT SUCCESS");

    }



  }


}

void SelectBaseStatement():
{}
{
  SelectList()
  "FROM"
  TableList()
  //该加中括号的要加
  [WhereStatement()]
//  [ WhereStatement() ]
//  [ GroupByStatement() ]
// 
//  

  {
    if(MySQL.state==MySQL.SDT){
      if(SQL_select.isIsWhere()==true){
        //先执行result,然后打印
      }else{
        if(SQL_select.isIsStart()==true){
          //全部打印,按照指定表
          System.out.println("* without where");
          try {
            SQL_select.PrintStarWithSingleTableWithoutWhere();
          } catch (IOException e) {
            // TODO Auto-generated catch block
           
          }



        }else{
          // TODO 按照指定列，和表来打印数据
          if(SQL_select.isIsWhere()==true){
            // TODO 1有where的情况，先选择符合条件的行
          }else{
            // TODO 无where,按指定列打印
            try{
              SQL_select.PrintSpecifiedColumnsWithouWhere();

            }catch(IOException e){
              e.printStackTrace();

            }
           
          }

        }
      }

    }



  }


  



}
//表名 单独处理
void TableList():
{}
{
//  IdentifierItem()("," IdentifierItem())*
//  TableItem()//("," TableItem())*
  SelectTableItem()("," SelectTableItem())*
  {


    // System.out.println(" selectBase ");
  }

}

//注意不要重名
//void TableItem():
//{}
//{
//  IdentifierItem()
//}

void SelectTableItem():
{Token temp;}
{
  temp=IdentifierItem()
   { 
    if(MySQL.state==MySQL.AST){
       System.out.println("TableName = "+temp);
    }


    if(MySQL.state==MySQL.SDT){
      System.out.println("TableName = "+temp);
      SQL_select.getTableName().add(temp.toString());

    }





   }
}

//列名 单独处理
void SelectList():
{Token temp;}
{
    (("*" )
    {

      if(MySQL.state==MySQL.AST){
        System.out.println("Columnse = ALL");
      }


      if(MySQL.state==MySQL.SDT){
        
      
      SQL_select.setIsStart(true);
    
        
      }




    }      )

    | 
    (SelectItem() ("," SelectItem())*)
}

void SelectItem():
{Token temp;}
{
  
  temp = IdentifierItem()
  {  
    if(MySQL.state==MySQL.AST){
      System.out.println("ColumnsName = "+temp);
    }

    if(MySQL.state==MySQL.SDT){
      System.out.println("ColumnsName = "+temp);
      if(SQL_select.isIsStart()==false){
        SQL_select.getShowColumn().add(temp.toString());

      }


    }
  
  }
}

// 比较运算符	=,<,>,<=,>=,<>	比较两个表达式
// 逻辑运算符	AND ,OR, NOT	组合两个表达式的运算结果或取反
// 范围运算符	BETWEEN,NOT BETWEEN	搜索值是否在范围内
// 列表运算符	IN,NOT IN	查询值是否属于列表值之一
// 字符匹配符	LIKE ,NOT LIKE	字符串是否匹配
// 未知值	IS NULL ,IS NOT NULL	查询值是否为NULL
void WhereStatement():
{}
{
  "WHERE"

  {
    if(MySQL.state==MySQL.SDT){
      SQL_select.setIsWhere(true);
      }

  }
  
  SQLCondition()(SQLCondition())*
  {
    if(MySQL.state==MySQL.SDT){
      System.out.println("开始批量执行OR操作");
      SQL_select.columnTools.OperationOr();
      }
  }

  
}
// %	任意多个字符	H% 表示查询以H开头的任意字符串,如Hello —– %h 表示查询以h结尾的任意字符串，如Growth —— %h% 表示查询在任何位置包含字母的h的所有字–符串，如hui，zhi
// _	单个字符	H_ 表示查询以H开头，后面跟任意一个字符的两位字符串，如Hi，He
// []	指定范围的单个字符	H[ea]% 表示查询以H开头，第二个字符是e或a的所有字符串，如：Health，Hand ———- [A-G]% 表示查询以A到G之间的任意字符开头的所有字符串，如：Apple，Banana，Guide
// [^]	不在指定范围的单个字符	H[^ea]% 表示查询以H开头，的一个字符不是e或a的所有字符串，如：Hope，Hub ——— [^A_G]% 表示查询不是以A到G之间的任意字符开头的字符串，如；Job，Zoo


//这里SQLCondition 和  SQLLogicalExpression 
//内部都有括号 所以容易产生冲突
void SQLCondition():
{}
{
//  ( "(" )*
  
  (
   SQLLogicalExpression() 
   ( "AND"
   {
    if(MySQL.state==MySQL.AST){
      System.out.println("AND");
      }

      if(MySQL.state==MySQL.SDT){
        SQL_select.columnTools.Operation.add("AND");
        }

   }
   
   SQLLogicalExpression())*


   ( "OR"
   {
    if(MySQL.state==MySQL.AST){
      System.out.println("OR");
      }

      if(MySQL.state==MySQL.SDT){
        SQL_select.columnTools.Operation.add("OR");
      }



   }
   
   SQLLogicalExpression())*

  )


  
//  ( ")" )*
}
//逻辑表达式
void SQLLogicalExpression():
{
  Token temp1,temp2,temp3;
}
{
  ( "(" )*

  (temp1=IdentifierItem()
  temp2=compare()
  temp3=IdentifierItem())
  

  ( ")" )*
  {
    if(MySQL.state==MySQL.AST){
      System.out.println("LEFT = "+temp1);
      System.out.println("LOGICAL = "+temp2);
      System.out.println("RIGHT = "+temp3);
    }

    if(MySQL.state==MySQL.SDT){
      System.out.println("LEFT = "+temp1);
      System.out.println("LOGICAL = "+temp2);
      System.out.println("RIGHT = "+temp3);


      if(SQL_select.columnTools.Operation.get(SQL_select.columnTools.Operation.size()-1)=="AND"){
        System.out.println("and 操作");
        SQL_select.columnTools.OperationAnd(temp1.toString(),temp2.toString(),temp3.toString());

		
        SQL_select.columnTools.Operation.remove(SQL_select.columnTools.Operation.size()-1);
      }else{

        SQL_select.columnTools.getColumnName().add(temp1.toString());
        SQL_select.columnTools.getCompareTo().add(temp2.toString());
        SQL_select.columnTools.getColumnValue().add(temp3.toString());
      }

    }




  }

}


void GroupByStatement():
{}
{
  "GROUP" "BY"
//  IdentifierItem()
}



void HAVINGStatement():
{}
{
  "HAVING" 
//  IdentifierItem()
}

void OrderByStatement():
{}
{
  "ORDER" "BY"
//  IdentifierItem()
}




//DELETE FROM 表名称 WHERE 列名称 = 值
void DeleteStatement():
{}
{
  "DELETE"
  [SelectList()]
   "FROM"
  TableList()
  [WhereStatement()]
//  IdentifierItem()
  ";"
  {
    if(MySQL.state==MySQL.LEX)
    System.out.println("DeleteStatement RIGHT");
  }

}





//UPDATE 表名称 SET 列名称 = 新值 WHERE 列名称 = 某值
void UpdateStatement():
{}
{
  "UPDATE"
  TableList()
  "SET"
  SQLCondition()("," SQLCondition())*
  [WhereStatement()]
//  IdentifierItem()


  ";"
  {
    if(MySQL.state==MySQL.LEX)
    System.out.println("UpdateStatement RIGHT");
  }


}



void ObjectName():
{}
{
    <SQL_IDENTIFIER> | <SQL_QUOTED_IDENTIFIER>
}



Token IdentifierItem():
{
  Token Token;
}
{
 ( (<SQL_IDENTIFIER> ["." <SQL_IDENTIFIER>] )
  |  (<SQL_BIND>)
  | ( <SingleQuotes> <SQL_IDENTIFIER> <SingleQuotes>)
  | (<SQL_CHAR_LITERAL>)
  |  < SQL_CONSTANT>)
  {
    return MySQL.token;
  }
}



// void CreatTable():
// {}{
 
// }


// void CreatTable():
// {}{
 
// }





// void CreatTable():
// {}{
 
// }


